# file: postgresql/tasks/users.yml

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

# Uncomment for science.
#- debug: msg="{{ item.name }} - md5{{ (item.pass + item.name) | md5 }}"
#  with_items: postgresql_users
#  when: postgresql_users|length > 0

# http://docs.ansible.com/ansible/postgresql_user_module.html
# 'str["md5"] + md5[ password + username ]'
- name: PostgreSQL | Make sure the PostgreSQL users are present
  postgresql_user:
    name: "{{ item.name }}"
    encrypted: yes
    password: "md5{{ (item.pass + item.name) | md5 }}"
    port: "{{ postgresql_port }}"
    state: present
    login_user: "{{ postgresql_admin_user }}"
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  with_items: "{{ postgresql_users }}"
  when: postgresql_users|length > 0
